### Starting the silos 2018 dataset

In [1]:
import pandas as pd
import os 
import numpy as np
from sklearn.model_selection import train_test_split
import numpy as np 

In [2]:
data = pd.read_parquet('../datasets/cic-ids2018dataset/datasets/Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet')
data.head(5)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,6,141385,9,7,553,3773.0,202,0,61.444443,87.534439,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,6,281,2,1,38,0.0,38,0,19.000000,26.870058,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,6,279824,11,15,1086,10527.0,385,0,98.727272,129.392502,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,6,132,2,0,0,0.0,0,0,0.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,6,274016,9,13,1285,6141.0,517,0,142.777771,183.887726,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign


In [3]:
### Combining all the datasets 
silo_path = '../datasets/cic-ids2018dataset/datasets/'
datasets = []

for filename in os.listdir(silo_path):
    if filename.endswith('.parquet'):
        filepath = os.path.join(silo_path, filename) ### Creating a file path for each directory
        data = pd.read_parquet(filepath)
        datasets.append(data)
    
combined_datasets = pd.concat(datasets, ignore_index=True)
combined_datasets.head(5)
print(combined_datasets.shape[0])

6659532


In [4]:
print(combined_datasets['Label'].value_counts())

Label
Benign                      5329008
DDoS attacks-LOIC-HTTP       575364
DDOS attack-HOIC             198861
DoS attacks-Hulk             145199
Bot                          144535
Infilteration                118483
SSH-Bruteforce                94048
DoS attacks-GoldenEye         41406
DoS attacks-Slowloris          9908
DDOS attack-LOIC-UDP           1730
Brute Force -Web                568
Brute Force -XSS                229
SQL Injection                    85
DoS attacks-SlowHTTPTest         55
FTP-BruteForce                   53
Name: count, dtype: int64


In [7]:
## Only the attack samples 
attack_data = combined_datasets[combined_datasets['Label'] != 'Benign']
benign_data = combined_datasets[combined_datasets['Label'] == 'Benign']

In [13]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
NUM_CLIENTS = 4
ALPHA = 0.5
for label in attack_data['Label'].unique():    
    indices = attack_data[attack_data['Label'] == label].index.to_numpy().copy() ## This returns the row number of each attack type sample
    np.random.shuffle(indices)
    proportions = np.random.dirichlet([ALPHA] * NUM_CLIENTS)
    print(label)
    print(proportions)



DDoS attacks-LOIC-HTTP
[9.26216357e-01 2.03265444e-02 5.85443163e-05 5.33985547e-02]
Brute Force -Web
[0.42714462 0.08409038 0.1290633  0.3597017 ]
Brute Force -XSS
[0.28074979 0.22565435 0.43609297 0.05750289]
SQL Injection
[0.01096896 0.0339979  0.95155134 0.00348179]
Bot
[0.03687025 0.41229033 0.08381809 0.46702133]
DDOS attack-LOIC-UDP
[0.29181324 0.36951801 0.32174892 0.01691983]
DDOS attack-HOIC
[6.32405657e-04 3.02404470e-04 7.54692786e-01 2.44372403e-01]
DoS attacks-SlowHTTPTest
[0.2023737  0.12588634 0.03195276 0.6397872 ]
DoS attacks-Hulk
[0.04596617 0.36018888 0.45799022 0.13585473]
DoS attacks-GoldenEye
[0.33133741 0.36584255 0.14498679 0.15783325]
DoS attacks-Slowloris
[0.00189515 0.11123072 0.10475673 0.7821174 ]
Infilteration
[0.25785693 0.03687488 0.69026476 0.01500343]
FTP-BruteForce
[0.82057836 0.07792889 0.08394038 0.01755238]
SSH-Bruteforce
[0.82780393 0.00116714 0.06095605 0.11007288]
